# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks. 
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  # node: circleci/node@4.7.0
  node: circleci/node@5.0.0

jobs:
  lint:
    # These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
    # You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # A list of available CircleCI Docker Convenience Images are available here: https://circleci.com/developer/images/image/cimg/node
    docker:
      - image: cimg/node:14.19
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn lint
  audit:
    docker:
      - image: cimg/node:14.19
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          # command: yarn audit
          command: yarn audit --groups dependencies
  tests:  
    docker:
      - image: cimg/node:14.19
      - image: circleci/mongo:5.0.6-ram
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn 
      - run:
          name: Run tests
          command: yarn test.ci
  coverage:  
    docker:
      - image: cimg/node:14.19
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn 
      - run:
          name: Run tests with coverage
          command: yarn test.ci --coverage
  deploy-dev:  
    docker:
      - image: cimg/node:14.19
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn 
      - run:
          name: Deploy to Dev
          command: yarn deploy.dev
  deploy-prod:  
    docker:
      - image: cimg/node:14.19
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn 
      - run:
          name: Deploy to Prod
          command: yarn deploy.prod

workflows:
  # Configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  check-and-build: 
    jobs:
      - lint
      - audit
      - tests:
          # context: AWS
      - coverage:
          # context: AWS
          requires:
           - tests
      ## Nothing to deploy for the template
      # - deploy-dev:
      #     context: AWS
      # - deploy-prod:
      #     context: AWS
      #     requires:
      #      - tests
      #      - lint
      #      - audit
      #      - deploy-dev
      #     filters:
      #       branches:
      #         only: master

## Advanced workflow - NodeJS version matrix

# workflows:
#   sample:
#     jobs:
#       - node/test:
#           matrix:
#             parameters:
#               version: ['15.1', 'lts', '12.21']
#           # For more information about matrix testing see the detailed blog post:
#           # https://circleci.com/blog/circleci-matrix-jobs/
#           # or the configuration reference:
#           # https://circleci.com/docs/2.0/configuration-reference/?section=reference#matrix-requires-version-21
