# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks. 
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.1

jobs:
  lint:
    docker:
      - image: cimg/node:14.17
    # executor:
    #   name: node/default
    #   tag: '14.17'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn lint
  audit:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn audit --groups dependencies
  unit-tests:  
    # These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
    # You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # A list of available CircleCI Docker Convenience Images are available here: https://circleci.com/developer/images/image/cimg/node
    docker:
      - image: cimg/node:14.17
    steps:
      # Checkout the code as the first step.
      - checkout
      - node/install-packages:
          pkg-manager: yarn 
      - run:
          name: Run tests
          command: yarn test

workflows:
  # Below is the definition of your workflow.
  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build-and-test job above.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  check-and-build: 
    jobs:
      - lint
      - audit
      - unit-tests
      - deploy-dev:
        requires:
          - unit-tests
          - lint
          - audit
          # - e2e-test
          # - performance-test
        filters:
          branches:
            only: master


## Advanced workflow - NodeJS version matrix

# workflows:
#   sample:
#     jobs:
#       - node/test:
#           matrix:
#             parameters:
#               version: ['15.1', 'lts', '12.21']
#           # For more information about matrix testing see the detailed blog post:
#           # https://circleci.com/blog/circleci-matrix-jobs/
#           # or the configuration reference:
#           # https://circleci.com/docs/2.0/configuration-reference/?section=reference#matrix-requires-version-21
